export const gameState = {
    unitSize: 25,
    isRunning: true,
    lastTime: 0,
    accumulator: 0,
    gameSpeed: 1000 / 10,
    direction: { x: 1, y: 0 },
    nextDirection: { x: 1, y: 0 },
    score: 0,
    lastTailPosition: null,
    wallCollision: true,
    perksUnlocked: false,
};

export const modeState = {
    modeSelected: "normal",
    modes: {
        normal: { unlocked: true },
        hard: { unlocked: false },
        expert: { unlocked: false },
        master: { unlocked: false },
        inferno: { unlocked: false },
    },
};

export const foodState = {
    eatenFoodPositions: [],
    currentSpecialFood: null, //WHAT FOOD IS CHOSEN
    specialFoodSpawnTimer: 3000, //TIMER BEFORE FUNCTION CALL

    foods: [
        {
            id: "apple",
            isSpecial: false,
            unlocked: true,
            spawnChance: 100,
            timer: 0,
            position: null,
            visible: true,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 1, hard: 2, expert: 3, master: 4, inferno: 5 },
        },
        {
            id: "carrot",
            isSpecial: true,
            unlocked: false,
            spawnChance: 100,
            timer: 4000,
            position: null,
            visible: false,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 3, hard: 6, expert: 9, master: 12, inferno: 15 },
        },
        {
            id: "banana",
            isSpecial: true,
            unlocked: false,
            spawnChance: 25,
            timer: 4000,
            position: null,
            visible: false,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 9, hard: 18, expert: 27, master: 36, inferno: 45 },
        },
        {
            id: "apricot",
            isSpecial: true,
            unlocked: false,
            spawnChance: 15,
            timer: 4000,
            position: null,
            visible: false,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 18, hard: 36, expert: 54, master: 62, inferno: 90 },
        },
        {
            id: "watermelon",
            isSpecial: true,
            unlocked: false,
            spawnChance: 10,
            timer: 3000,
            position: null,
            visible: false,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 20, hard: 40, expert: 60, master: 80, inferno: 100 },
        },
        {
            id: "avocado",
            isSpecial: true,
            unlocked: false,
            spawnChance: 5,
            timer: 3000,
            position: null,
            visible: false,
            timeLeft: 0,
            totalCollected: 0,
            points: { normal: 18, hard: 36, expert: 54, master: 62, inferno: 90 },
        },
    ],
};
